
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: sketch
      description: "A starter dbt model to pull redshift data"
      columns:
          - name: catid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
